export enum DamageType {
  DEFORESTATION = 'DESMATAMENTO',
  FIRE = 'INCENDIO',
  WATER_POLLUTION = 'POLUICAO_HIDRICA',
  ANIMAL_ABUSE = 'MAUS_TRATOS_ANIMAL',
  ILLEGAL_MINING = 'EXTRACAO_MINERAL_ILEGAL',
  LAND_INVASION = 'INVASAO_DE_TERRA',
  OIL = 'COMBUSTÍVEL_ADULTERADO',
  OTHER = 'OUTRO',
}