export enum DocumentType {
  PRELIMINARY_REPORT = 'LAUDO_PRELIMINAR',
  DEFINITIVE_REPORT = 'LAUDO_DEFINITIVO',
  REQUEST_FORM = 'GUIA_DE_REQUISICAO',
  MEMORANDUM = 'MEMORANDO',
  LAUDO_PERICIAL_CRIMINAL = 'LAUDO_PERICIAL',
  ERRATUM = 'ERRATA', // Para a lógica de correção de documentos
  OTHER = 'OUTRO',
}